import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF8F0',
  },
  gradient: {
    flex: 1,
    flexDirection: 'column',
  },
  contentWrapper: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  paginationInfo: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#FFFBF7',
    borderBottomWidth: 1,
    borderBottomColor: '#F0E6D8',
  },
  paginationText: {
    fontSize: 13,
    color: '#CD7F32',
    fontWeight: '600',
    textAlign: 'center',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 38,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F0E6D8',
    backgroundColor: '#FFFFFF',
  },
  backButton: {
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
    backgroundColor: '#FFF5EB',
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#2C2C2C',
    letterSpacing: 0.5,
    marginLeft: 12,
  },
  listContent: {
    paddingHorizontal: 12,
    paddingVertical: 16,
    paddingBottom: 100,
  },
  columnWrapper: {
    justifyContent: 'space-between',
    paddingHorizontal: 4,
    marginBottom: 16,
  },
  cardWrapper: {
    flex: 1,
    marginHorizontal: 4,
  },
  card: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#CD7F32',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 5,
  },
  cardImage: {
    width: '100%',
    height: 160,
    backgroundColor: '#F5F5F5',
    position: 'relative',
  },
  favoritoButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  image: {
    width: '100%',
    height: '100%',
  },
  imagePlaceholder: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F0E6D8',
  },
  cardContent: {
    padding: 14,
  },
  receitaNome: {
    fontSize: 15,
    fontWeight: '700',
    color: '#2C2C2C',
    marginBottom: 8,
    lineHeight: 20,
  },
  receitaTempo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  receitaTempoText: {
    fontSize: 13,
    color: '#666666',
    marginBottom: 0,
    fontWeight: '500',
    marginLeft: 6,
  },
  receitaInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  receitaNotaContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  receitaNota: {
    fontSize: 13,
    color: '#CD7F32',
    fontWeight: '700',
    marginLeft: 4,
  },
  receitaAvaliacoes: {
    fontSize: 12,
    color: '#999999',
    fontWeight: '500',
  },
  dataFavoritado: {
    fontSize: 11,
    color: '#999999',
    fontWeight: '400',
    marginTop: 6,
    fontStyle: 'italic',
  },
  footerLoader: {
    paddingVertical: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    minHeight: 400,
  },
  emptyText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2C2C2C',
    marginTop: 16,
    textAlign: 'center',
  },
  emptySubtext: {
    fontSize: 14,
    color: '#999999',
    marginTop: 8,
    textAlign: 'center',
  },
  skeletonContainer: {
    paddingHorizontal: 12,
    paddingVertical: 16,
  },
});

export default styles;
