import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF8F0',
  },
  gradient: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 28,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F0E6D8',
    backgroundColor: '#FFFFFF',
  },
  backButton: {
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
    backgroundColor: '#FFF5EB',
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#2C2C2C',
    letterSpacing: 0.5,
    marginLeft: 12,
  },
  imagemContainer: {
    width: '100%',
    height: 320,
    backgroundColor: '#F5F5F5',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  imagem: {
    width: '100%',
    height: '100%',
  },
  imagemPlaceholder: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F0E6D8',
  },
  tituloContainer: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 20,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 0,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  tituloContent: {
    flex: 1,
  },
  titulo: {
    fontSize: 28,
    fontWeight: '800',
    color: '#1A1A1A',
    lineHeight: 36,
    letterSpacing: -0.5,
  },
  favoritoButtonDetalhes: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#FFF5EB',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 12,
    shadowColor: '#CD7F32',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  infoContainer: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: '#FFF5EB',
    borderBottomWidth: 1,
    borderBottomColor: '#F0E6D8',
    justifyContent: 'space-around',
  },
  infoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  infoTexto: {
    marginLeft: 8,
  },
  infoLabel: {
    fontSize: 11,
    color: '#999999',
    fontWeight: '500',
  },
  infoValor: {
    fontSize: 14,
    color: '#2C2C2C',
    fontWeight: '600',
    marginTop: 2,
  },
  autorContainer: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 16,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#F0E6D8',
  },
  autorTexto: {
    marginLeft: 12,
    flex: 1,
  },
  autorLabel: {
    fontSize: 12,
    color: '#999999',
    fontWeight: '500',
  },
  autorNome: {
    fontSize: 16,
    color: '#2C2C2C',
    fontWeight: '600',
    marginTop: 2,
  },
  botaoAbrir: {
    flexDirection: 'row',
    backgroundColor: '#CD7F32',
    paddingVertical: 16,
    paddingHorizontal: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 16,
    marginVertical: 20,
    shadowColor: '#CD7F32',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 6,
  },
  botaoAbrirTexto: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 10,
    letterSpacing: 0.3,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: '#CD7F32',
    fontWeight: '600',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  errorText: {
    fontSize: 16,
    color: '#666666',
    textAlign: 'center',
    marginTop: 12,
  },
  espacoExtra: {
    height: 20,
  },
  secaoContainer: {
    paddingHorizontal: 16,
    paddingVertical: 20,
    marginVertical: 8,
    marginHorizontal: 8,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderBottomWidth: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  secaoTitulo: {
    fontSize: 18,
    fontWeight: '800',
    color: '#CD7F32',
    marginBottom: 14,
    letterSpacing: -0.3,
  },
  descricaoTexto: {
    fontSize: 14,
    color: '#444444',
    lineHeight: 24,
    fontWeight: '500',
  },
  ingredienteItem: {
    flexDirection: 'row',
    marginBottom: 12,
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: '#FFF9F5',
    borderRadius: 8,
  },
  ingredienteBullet: {
    fontSize: 20,
    color: '#CD7F32',
    marginRight: 12,
    fontWeight: '700',
    marginTop: -2,
  },
  ingredienteTexto: {
    fontSize: 14,
    color: '#333333',
    flex: 1,
    lineHeight: 22,
    fontWeight: '500',
    marginLeft: 10,
  },
  passoItem: {
    flexDirection: 'row',
    marginBottom: 16,
    alignItems: 'flex-start',
  },
  passoNumero: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#CD7F32',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
    marginTop: 0,
    shadowColor: '#CD7F32',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  passoNumeroTexto: {
    fontSize: 16,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  passoTexto: {
    fontSize: 14,
    color: '#333333',
    flex: 1,
    lineHeight: 24,
    paddingTop: 4,
    fontWeight: '500',
  },
  informacoesTexto: {
    fontSize: 14,
    color: '#444444',
    lineHeight: 24,
    fontWeight: '500',
  },
});

export default styles;
